version: "3.8"
services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  db_pars:
    container_name: db_pars
    ports:
      - "5432:5432"
    image: postgres:latest
    environment:
        POSTGRES_USER: parser
        POSTGRES_PASSWORD: parser
        POSTGRES_DB: db_pars
  backend:
    container_name: backend
    ports:
      - "1323:1323"
    image: backend:latest
    build:
        context: .
        dockerfile: Dockerfile-backend
    depends_on:
        - db_pars
        - redis
